version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - save_cache:
          paths:
            - "node_modules"
          key: "npm_packages"
  test:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache: "npm_packages"
      - run: npm run test
  analyze:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache: "npm_packages"
      - run: npm audit

workflows:
  CI-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
